package dev.bibbelventure.utility.drawio;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * Drawio node data bean.
 * Assumes a mandatory unique id and optionally additional attributes stored as metadata
 *
 * @author raschke
 */
public class DrawioNode
{
    // mandatory unique id from Drawio
    private final String id;
    // other optional metadata attributes
    private final Map<String, String> metadata;
    // other nodes connected via arrows in Drawio
    private final Set<String> connectedNodeIds;

    /**
     * Constructor.
     *
     * @param id - mandatory unique id, generated by Drawio
     */
    public DrawioNode( String id )
    {
        this.id = id;
        this.metadata = new HashMap<>();
        this.connectedNodeIds = new HashSet<>();
    }

    public void addMetadata( String key, String value )
    {
        metadata.put( key, value );
    }

    public String getId()
    {
        return id;
    }

    public Map<String, String> getMetadata()
    {
        return metadata;
    }

    public Set<String> getConnectedNodeIds()
    {
        return connectedNodeIds;
    }

}
